### ISSUE TITLE
to-do list from meeting with Amanda and Jill

### ISSUE THREAD

**Issue by sformel-usgs** [kylieh10/gomx_sediment_macrofauna#10]
@kylieh10 could you work on these please?

- [x] In IPT, infer EML geographic, taxonomic, temporal scope from data
- [x] `measurementUnit` needs a literal label, not the acronym
- [x] add length of core to samplingProtocol? somewhere else?

**Comment by kylieh10** [comment]
I'm not sure if there was a need to update geographic or temporal scopes, but I did add taxonomic (from the infer function)
